dist: trusty

jobs:
    include:
        - stage: Build docker php7light
          script:
            - echo "$DOCKER_PASSWORD" | docker_login -u "$DOCKER_USERNAME" --password-stdin
            - docker build -t php7light .
            - docker images
            - docker tag php7light $DOCKER_USERNAME/php7light
            - docker push $DOCKER_USERNAME/php7light
        - stage: test
          script: docker run --rm $DOCKER_USERNAME/php7light composer --version
